# Name of your workflow
name: build and run tests

#Define the trigger event(s)
on: 
  push: 
    branches: [testing-1]
  pull_request:
    branches: [master]

jobs:

  windows_test:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing bat file
        run: |
           build.bat test
      - name: Running images
        run: |
           build.bat run



       