# Name of your workflow
name: My Test Workflow

#Define the trigger event(s)
on: 
  push: 
    branches: [master]

# Jobs run in parallel by default, each runs steps 
jobs: 
    #Job to print something out
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello, GitHub actions!"
    build-and-test:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
          run-test: true
          ctest-options: -R mytest
          # install the build using cmake --install
          install-build: true
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 14