# Name of your workflow
name: My Test Workflow

#Define the trigger event(s)
on: 
  push: 
    branches: [master]

# Jobs run in parallel by default, each runs steps 
jobs: 
    #Job to print something out
    say-hello:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello, GitHub actions!"
    build-and-test:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - name: configure
      run: mkdir build && cd build && cmake .. -G "Unix Makefiles"

    