# Name of your workflow
name: build and run tests

#Define the trigger event(s)
on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: boost
      run: sudo apt-get update && sudo apt-get install
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cd build && cmake .. -G "Unix Makefiles" && make -B



       