# Name of your workflow
name: My Test Workflow

#Define the trigger event(s)
on: 
  push: 
    branches: [master]

# Jobs run in parallel by default, each runs steps 
jobs: 
    build-and-test:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v3

      - name: Configure CMake

        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

       