# Name of your workflow
name: Unit Test Windows

#Define the trigger event(s)
on: 
  push: 
    branches: [testing-1]

jobs:

  windows_test:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
        dotnet-version: '6.0.x'
    
      - name: Testing bat file
        shell: bash
        run: |
         mkdir build
         cd build
         cmake .. -Wno-dev -Werror -G "Unix Makefiles"
         cmake --build . --parallel 
      - name: Running images
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --output-on-failure
          