# Name of your workflow
name: Unit Test Windows

#Define the trigger event(s)
on: 
  push: 
    branches: [testing-1]

jobs:

  windows_test:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
         submodules: true
      - name: Setup tmate session
        if: ${{failure()}}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      # - run: exit 1
      - name: Testing bat file
        run: |
         mkdir build
         cd build
         cmake .. -G "Unix Makefiles"
         cmake --build . --parallel 
         ctest --output-on-faiulre --test-dir build/bin
      