# Name of your workflow
name: Unit Test Windows

#Define the trigger event(s)
on: 
  push: 
    branches: [testing-1]

jobs:

  windows_test:
    runs-on: windows-2019
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
         submodules: true
      - name: Setup tmate session

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Testing bat file
        run: |
         mkdir build
         cd build
         cmake .. -G "Unix Makefiles"
         cmake --build . --parallel 
         ctest --verbose
      